CREATE DATABASE library;

CREATE TABLE library.person
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR UNIQUE NOT NULL,
    year_of_birth INT            NOT NULL CHECK ( year_of_birth > 0 )
);

CREATE TABLE library.book
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR UNIQUE NOT NULL,
    author VARCHAR        NOT NULL,
    year   INT CHECK ( year > 0 )
)